/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "connection_info": {                             "en": "Connection settings",                             "de": "Verbindung-Einstellungen",                        "ru": "Параметры подключения ",                          "pt": "Configurações de conexão",                        "nl": "Instellingen verbinding",                         "fr": "Paramètres de connexion",                         "it": "Impostazioni di connessione",                     "es": "Configuración de la conexión",                    "pl": "Ustawienia połączenia ",                          "zh-cn": "连接设置"},
    "delete": {                                      "en": "delete",                                          "de": "löschen",                                         "ru": "удалить",                                         "pt": "apagar",                                          "nl": "verwijderen",                                     "fr": "supprimer",                                       "it": "eliminare",                                       "es": "eliminar",                                        "pl": "usunąć",                                          "zh-cn": "删除"},
    "enabled": {                                     "en": "enabled",                                         "de": "aktiviert",                                       "ru": "включен",                                         "pt": "habilitado",                                      "nl": "ingeschakeld",                                    "fr": "activé",                                          "it": "abilitato",                                       "es": "habilitado",                                      "pl": "włączony",                                        "zh-cn": "启用"},
    "encryptionKey": {                               "en": "Encryption Key for Payload Encryption",           "de": "Der Verschlüsselungs-Schlüssel für Payload-Verschlüsselung", "ru": "Ключ шифрования для шифрования полезной нагрузки ", "pt": "A criptografia de Chave para Criptografia de Carga útil", "nl": "Encryptie Sleutel voor Payload Encryption",       "fr": "Clé de chiffrement pour le Chiffrement des données utiles", "it": "Chiave di crittografia per la Crittografia Payload", "es": "Clave de cifrado para la Encriptación de la Carga útil", "pl": "Klucz do szyfrowania ładunku ",                   "zh-cn": "加密钥对于有效负荷加密"},
    "mqtt": {                                        "en": "MQTT instance",                                   "de": "MQTT-Instanz",                                    "ru": "Экземпляр протоколу MQTT ",                       "pt": "DICIONÁRIO de instância",                         "nl": "MQTT exemplaar",                                  "fr": "MQTT exemple",                                    "it": "MQTT istanza",                                    "es": "MQTT instancia",                                  "pl": "Egzemplarz protokołu MQTT ",                      "zh-cn": "过实例"},
    "picture": {                                     "en": "Picture",                                         "de": "Bild",                                            "ru": "Картинка",                                        "pt": "Imagem",                                          "nl": "Foto",                                            "fr": "Image",                                           "it": "Foto",                                            "es": "Imagen",                                          "pl": "Obraz",                                           "zh-cn": "图片"},
    "pictures_info": {                               "en": "User Pictures",                                   "de": "User-Bilder",                                     "ru": "Фотографии Пользователя ",                        "pt": "Fotos Do Usuário",                                "nl": "Gebruikers Foto ' S",                             "fr": "L'Utilisateur Photos",                            "it": "Foto Utente",                                     "es": "Fotos De Los Usuarios",                           "pl": "Zdjęcia Użytkownika ",                            "zh-cn": "用户的照片"},
    "tab_config": {                                  "en": "Configuration",                                   "de": "Konfiguration",                                   "ru": "Конфигурации",                                    "pt": "Configuração",                                    "nl": "Configuratie",                                    "fr": "Configuration",                                   "it": "Configurazione",                                  "es": "Configuración",                                   "pl": "Konfiguracji",                                    "zh-cn": "配置"},
    "tab_info": {                                    "en": "Information",                                     "de": "Informationen",                                   "ru": "Информация",                                      "pt": "Informações",                                     "nl": "Informatie",                                      "fr": "Informations",                                    "it": "Informazioni",                                    "es": "Información",                                     "pl": "Informacje",                                      "zh-cn": "的信息"},
    "tab_setup": {                                   "en": "Setup instructions",                              "de": "Setup-Anweisungen",                               "ru": "Инструкция по установке ",                        "pt": "Instruções de instalação",                        "nl": "Installatie-instructies",                         "fr": "Instructions d'installation",                     "it": "Istruzioni per l'installazione",                  "es": "Instrucciones de instalación",                    "pl": "Instrukcja instalacji ",                          "zh-cn": "设置说明"},
    "togglePassword": {                              "en": "show / hide password",                            "de": "ein - / ausblenden Passwort",                     "ru": "Показать / Скрыть пароль",                        "pt": "mostrar / ocultar a senha",                       "nl": "tonen / verbergen van een wachtwoord",            "fr": "afficher / masquer le mot de passe",              "it": "mostra / nascondi la password",                   "es": "mostrar / ocultar la contraseña",                 "pl": "Pokaż / Ukryj hasło",                             "zh-cn": "显示出隐藏的密码"},
    "upload": {                                      "en": "upload",                                          "de": "hochladen",                                       "ru": "загрузить",                                       "pt": "upload",                                          "nl": "upload",                                          "fr": "télécharger",                                     "it": "caricare",                                        "es": "subir",                                           "pl": "pobierz",                                         "zh-cn": "上传"},
    "name": {                                        "en": "User",                                            "de": "Benutzer",                                        "ru": "Пользователь",                                    "pt": "Utilizador",                                      "nl": "Gebruiker",                                       "fr": "L'utilisateur",                                   "it": "Utente",                                          "es": "Usuario",                                         "pl": "Użytkownik",                                      "zh-cn": "用户"},
};